modLoader="javafml"
loaderVersion="[2,)"
license="Not specified"

[[mods]]
modId="elemental_tribes"
version="1.0.0"
displayName="Elemental Tribes"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="rockm, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.elemental_tribes]]
    modId="neoforge"
    type="required"
    versionRange="[20.6.117,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.elemental_tribes]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.elemental_tribes]]
    modId="curios_api"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.elemental_tribes]]
    modId="geckolib"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


[[mixins]]
    config="mixins.elemental_tribes.json"

# Start of user code block dependencies configuration
# End of user code block dependencies configuration